### ISSUE TITLE
Docker contaner been created

### ISSUE THREAD

**Issue by mdef** [atoomic/snapcast-volume-ui#11]
FUI:
Feel free to test it ubuntu:16.04 based
https://hub.docker.com/r/mdef/snapcast-volume-ui/

**Comment by atoomic** [comment]
Excellent, thanks for sharing this. 
We should add a section to the doc for it, do you mind submitting a merge request with it?

**Comment by atoomic** [comment]
thanks @mdef added to the doc via 41db049133ecd5c52bf18ffca4bd405386c502cc
