### ISSUE TITLE
Ignore list appears to be case-sensitive

### ISSUE THREAD

**Issue by airdrummingfool** [atoomic/snapcast-volume-ui#3]
Hello,
I recently needed to ignore a client on my network, so I moved the MAC address from the config section into the ignore list. However, the client continued to show up. I then changed all characters to lowercase (e.g. `12:AB:3C` to `12:ab:3c`), and the client was properly ignored. This surprised me because uppercase MAC addresses work fine in the config list, and MAC addresses display in the UI in all caps.

Thanks!

**Comment by atoomic** [comment]
thanks for the report this is fixed with 9c65dc0

**Comment by airdrummingfool** [comment]
Wow, incredibly fast turnaround. Thanks!
